server:
  port: 8082

spring:
    data:
        mondodb:
            host: localhost
            port: 27017
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true            