server:
  port: 8085

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nitesh2529/ConfigServer
          # clone-on-start: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
          